Link to destination channel; drop New Voter! prefix; TEAM_ID in environment
tomerovadia/VoterHelpLine pull request #132
Opened 2020-10-16 14:58 UTC by liewegas

2020-10-16 15:11 UTC, benweissmann requested changes

2020-10-16 15:11 UTC, benweissmann commented on .env.test
> +TEAM_ID=test_slack_team_id
Can you add how to get this to https://docs.google.com/document/d/1_zAwkDKnpcphb9hC2Oro4M-rdXkLLqpFnh_Nt5I19Sk/edit#heading=h.akt7k744o5cn ? And also make sure to ping Andrew/Tomer after this is merged so they can update their dev envs

2020-10-16 15:11 UTC, benweissmann commented on src/router.ts
> +  const closedVoterPanelMessage = `Voter has been routed to <slack://channel?team=${process.env.TEAM_ID}&id=${destinationSlackChannelId}|#${destinationSlackChannelName}>.`;
Maybe pull out a `linkToSlackChannel(channelId, channelName)` helper?

2020-10-17 15:14 UTC, tomerovadia approved these changes

2020-10-17 15:26 UTC, liewegas commented
@benweissmann okay to merge this one now?

2020-10-17 15:31 UTC, benweissmann approved these changes

2020-10-17 18:46 UTC, merged