/announce channel-status|volunteer-status [preamble]
tomerovadia/VoterHelpLine pull request #153
Opened 2020-10-19 15:28 UTC by liewegas

2020-10-20 05:01 UTC, tomerovadia requested changes
Added some minor comments. Happy to push to staging tomorrow (and can include Eli's changes as well, if you like them).

2020-10-20 05:01 UTC, tomerovadia commented on src/slack_interaction_handler.ts
> +  const what = args.shift();
Can you rename the `what` variable to something more descriptive?

2020-10-20 05:01 UTC, tomerovadia commented on src/slack_interaction_handler.ts
> +      const vstats = await DbApiUtil.getThreadsNeedingAttentionByVolunteer();
nit: can you rename vstats to volunteerStats?

2020-10-20 05:01 UTC, tomerovadia commented on src/slack_interaction_handler.ts
> +        const ulines = await getNeedsAttentionList(v.volunteerSlackUserId);
Can you rename ulines to something more descriptive?

2020-10-20 05:01 UTC, tomerovadia commented on external_config/slack.md
> +- **Command:** /announce
Can we rename /announce to something more specific?

2020-10-20 13:07 UTC, liewegas commented on external_config/slack.md
> +- **Command:** /announce
how about `/broadcast`?

2020-10-21 00:24 UTC, tomerovadia approved these changes

2020-10-21 00:46 UTC, merged