clear voter claims when resetting demo
tomerovadia/VoterHelpLine pull request #166
Opened 2020-10-22 16:19 UTC by liewegas

This obscures a complete history in the database, but these are demo
voters--we really don't care.  (And the table doesn't provide a way
to ignore claims pre-reset.)

2020-10-22 16:19 UTC, liewegas commented
Tryn ran into this one last night!

2020-10-23 03:59 UTC, tomerovadia reviewed
Is the purpose of this change ease of developing/QA, or something else?

The original use case for demo conversations requires that this `volunteer_voter_claims` history be persisted (for volunteer-to-volunteer practice and admin review of volunteer readiness). The history of voter claims provides a way to determine which volunteers answered which demo conversations, to be matched against their messages and then evaluated to determine if volunteers are prepared to take on real voters.

We can add an `archived` column similarly to what exists for the `messages` table: https://github.com/tomerovadia/VoterHelpLine/pull/79

That also allows us to keep the `volunteer_voter_claims` table write-only.

2020-10-23 15:17 UTC, liewegas commented
Much better.  Updated!

2020-10-23 23:08 UTC, tomerovadia requested changes
Looks good!

2020-10-23 23:08 UTC, tomerovadia commented on src/db_api_util.ts
> +export async function archiveDemoVoterClaims(
nit: can we name this archiveDemoVolunteerVoterClaims?

2020-10-23 23:08 UTC, tomerovadia commented on src/db_api_util.ts
> +  logger.info(`ENTERING DBAPIUTIL.clearDemoVoterClaims`);
update log line

2020-10-23 23:08 UTC, tomerovadia commented on src/db_api_util.ts
> +      `DBAPIUTIL.clearDemoVoterClaims: Successfully cleared demo voter claims.`
if you update the function name let's update the log line here too

2020-10-23 23:08 UTC, tomerovadia commented on sql/20201022.sql
> +ALTER TABLE volunteer_voter_claims
can you update the name of this file to today's date before merging?

2020-10-23 23:15 UTC, tomerovadia approved these changes

2020-10-23 23:41 UTC, merged